# Generated by Django 2.2.5 on 2020-09-20 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CityName', models.CharField(max_length=50, unique=True)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
                ('UpdateDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(blank=True, null=True, upload_to='')),
                ('Text', models.TextField(blank=True, null=True)),
                ('CreatedDate', models.DateField(auto_now_add=True)),
                ('UpdateDate', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NonTechnical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NonTechnicalName', models.CharField(max_length=250, unique=True)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
                ('UpdateDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Post_Title', models.CharField(max_length=50)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
                ('UpdateDate', models.DateField(auto_now_add=True)),
                ('LikeCount', models.IntegerField(default=0)),
                ('UnLikeCount', models.IntegerField(default=0)),
                ('Post_Content', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nsp_project_app.Content')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StateName', models.CharField(max_length=50, unique=True)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
                ('UpdateDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Technical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TechnicalName', models.CharField(max_length=250, unique=True)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
                ('UpdateDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, default='blank-headshot.jpg', upload_to='media/img')),
                ('Institute', models.CharField(blank=True, max_length=50)),
                ('Age', models.IntegerField(default=0)),
                ('BirthDate', models.DateField(blank=True, null=True)),
                ('CreatedDate', models.DateField(auto_now_add=True)),
                ('UpdateDate', models.DateField(auto_now_add=True)),
                ('Job_Status', models.BooleanField(default=0)),
                ('NonTechnicalField', models.ForeignKey(blank=True, null=True, on_delete=None, to='nsp_project_app.NonTechnical')),
                ('State_Name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nsp_project_app.State')),
                ('TechnicalField', models.ForeignKey(blank=True, null=True, on_delete=None, to='nsp_project_app.Technical')),
                ('city_Name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nsp_project_app.City')),
                ('email', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nsp_project_app.User_table')),
                ('username', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UnLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UnLikeCount', models.IntegerField(default=0)),
                ('Post', models.ForeignKey(blank=True, on_delete=None, to='nsp_project_app.post')),
                ('User', models.ForeignKey(blank=True, on_delete=None, to='nsp_project_app.User_info')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nsp_project_app.User_info'),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LikeCount', models.IntegerField(default=0)),
                ('Post', models.ForeignKey(blank=True, null=True, on_delete=None, to='nsp_project_app.post')),
                ('User', models.ForeignKey(blank=True, null=True, on_delete=None, to='nsp_project_app.User_info')),
            ],
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InstituteAddress', models.TextField(max_length=500)),
                ('InstitutePhoneNo', models.IntegerField(unique=True)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
                ('UpdateDate', models.DateTimeField(auto_now_add=True)),
                ('State_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nsp_project_app.State')),
                ('city_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nsp_project_app.City')),
                ('email', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nsp_project_app.User_table')),
                ('username', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.BooleanField(default=0)),
                ('FromUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Request_Sent', to='nsp_project_app.User_info')),
                ('ToUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendrequests', to='nsp_project_app.User_info')),
            ],
        ),
        migrations.CreateModel(
            name='Followig_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Following', models.ManyToManyField(blank=True, related_name='_followig_user_Following_+', to='nsp_project_app.Followig_User')),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Followings', to='nsp_project_app.User_info')),
            ],
        ),
        migrations.CreateModel(
            name='Followers_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Followers', models.ManyToManyField(blank=True, related_name='_followers_user_Followers_+', to='nsp_project_app.Followers_User')),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Followers', to='nsp_project_app.User_info')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Post_comment', models.TextField(max_length=250)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
                ('UpdateDate', models.DateTimeField(auto_now_add=True)),
                ('Post', models.ForeignKey(blank=True, on_delete=None, to='nsp_project_app.post')),
                ('User', models.ForeignKey(blank=True, on_delete=None, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='CityState',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nsp_project_app.State'),
        ),
    ]
