# Generated by Django 2.2.5 on 2020-10-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsp_project_app', '0003_auto_20201002_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institute',
            name='email',
        ),
        migrations.AlterField(
            model_name='user_info',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='User_table',
        ),
    ]
