# Generated by Django 2.2.5 on 2020-10-02 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nsp_project_app', '0006_auto_20201003_0414'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
