# Generated by Django 2.2.5 on 2020-10-02 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nsp_project_app', '0007_delete_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LikeCount', models.IntegerField(default=0)),
                ('Post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nsp_project_app.post')),
                ('User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nsp_project_app.User_info')),
            ],
        ),
    ]
