# Generated by Django 2.2.5 on 2020-10-03 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nsp_project_app', '0008_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='User',
        ),
    ]
