# Generated by Django 2.2.5 on 2020-10-03 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nsp_project_app', '0009_remove_like_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='User',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='nsp_project_app.User_info'),
            preserve_default=False,
        ),
    ]
