# Generated by Django 2.2.5 on 2020-10-03 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nsp_project_app', '0010_like_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='User',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nsp_project_app.User_info'),
        ),
        migrations.AlterField(
            model_name='unlike',
            name='User',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nsp_project_app.User_info'),
        ),
    ]
