# Generated by Django 2.2.5 on 2020-10-09 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsp_project_app', '0011_auto_20201003_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institute',
            name='username',
        ),
        migrations.AddField(
            model_name='user_info',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
