# Generated by Django 2.2.5 on 2020-10-09 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nsp_project_app', '0012_auto_20201009_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unlike',
            name='Post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nsp_project_app.post'),
        ),
    ]
