# Generated by Django 2.2.5 on 2020-10-09 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsp_project_app', '0015_auto_20201009_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='Post_comment',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
    ]
