# Generated by Django 2.2.5 on 2020-10-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsp_project_app', '0016_comment_post_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='img',
            field=models.ImageField(blank=True, default=None, upload_to='media/img'),
        ),
    ]
