# Generated by Django 2.2.5 on 2020-10-12 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsp_project_app', '0017_auto_20201009_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followers_user',
            name='Followers',
            field=models.ManyToManyField(blank=True, null=True, to='nsp_project_app.User_info'),
        ),
        migrations.AlterField(
            model_name='followig_user',
            name='Following',
            field=models.ManyToManyField(blank=True, null=True, to='nsp_project_app.User_info'),
        ),
    ]
