# Generated by Django 2.2.5 on 2020-10-12 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nsp_project_app', '0018_auto_20201012_0910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followig_user',
            name='Following',
        ),
        migrations.RemoveField(
            model_name='followig_user',
            name='User',
        ),
        migrations.DeleteModel(
            name='Followers_User',
        ),
        migrations.DeleteModel(
            name='Followig_User',
        ),
    ]
