# Generated by Django 2.2.5 on 2020-10-12 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nsp_project_app', '0019_auto_20201012_0913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Followig_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Following', models.ManyToManyField(blank=True, null=True, to='nsp_project_app.User_info')),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Followings', to='nsp_project_app.User_info')),
            ],
        ),
        migrations.CreateModel(
            name='Followers_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Followers', models.ManyToManyField(blank=True, null=True, to='nsp_project_app.User_info')),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Followers', to='nsp_project_app.User_info')),
            ],
        ),
    ]
