# Generated by Django 2.2.5 on 2020-10-12 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nsp_project_app', '0021_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='friend',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='nsp_project_app.FriendRequest'),
        ),
    ]
