# Generated by Django 2.2.5 on 2020-10-12 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nsp_project_app', '0022_notification_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='nsp_project_app.User_info'),
        ),
        migrations.AlterField(
            model_name='followers_user',
            name='Followers',
            field=models.ManyToManyField(to='nsp_project_app.User_info'),
        ),
        migrations.AlterField(
            model_name='followig_user',
            name='Following',
            field=models.ManyToManyField(to='nsp_project_app.User_info'),
        ),
    ]
