# Generated by Django 2.2.5 on 2020-10-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsp_project_app', '0023_auto_20201012_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
