# Generated by Django 2.2.5 on 2020-10-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsp_project_app', '0024_notification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.BooleanField(blank=True, default=0, max_length=10, null=True),
        ),
    ]
