# Generated by Django 2.2.5 on 2020-10-13 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nsp_project_app', '0025_auto_20201012_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='ToUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friendrequests', to='nsp_project_app.User_info'),
        ),
    ]
