# Generated by Django 2.2.5 on 2020-10-13 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nsp_project_app', '0026_auto_20201013_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='FromUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Request_Sent', to='nsp_project_app.User_info'),
        ),
    ]
