# Generated by Django 2.2.5 on 2020-10-15 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nsp_project_app', '0027_auto_20201013_1856'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Followers_User',
        ),
    ]
