# Generated by Django 2.2.5 on 2020-10-15 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nsp_project_app', '0028_delete_followers_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Followers_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Followers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nsp_project_app.User_info')),
                ('User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Followers', to='nsp_project_app.User_info')),
            ],
        ),
    ]
